-- ============================================================
-- heythere-crm Supabase Schema
-- Supabase SQL Editor에서 실행하세요.
-- ============================================================

-- customers
create table if not exists customers (
  id bigint generated by default as identity primary key,
  no integer not null,
  name text,
  phone text,
  "marketingConsent" text,
  "browserId" text,
  "customerId" text,
  "lastAccess" text,
  created_at timestamp with time zone default now()
);

-- send_history (고객 카카오 발송 이력)
create table if not exists send_history (
  id bigint generated by default as identity primary key,
  "customerId" text not null,
  date text,
  type text,
  template text,
  status text,
  created_at timestamp with time zone default now()
);

-- campaigns (CRM 캠페인)
create table if not exists campaigns (
  id bigint generated by default as identity primary key,
  no integer not null,
  name text,
  type text,
  "sendDate" text,
  status text,
  "targetCount" integer default 0,
  "successCount" integer default 0,
  "failCount" integer default 0,
  created_at timestamp with time zone default now()
);

-- marketing_records (마케팅 현황)
create table if not exists marketing_records (
  id bigint generated by default as identity primary key,
  no integer not null,
  name text,
  period text,
  type text,
  status text,
  "sendCount" text,
  target text,
  impressions integer default 0,
  clicks text,
  "avgClickTime" text,
  created_at timestamp with time zone default now()
);

-- point_history (포인트 충전/사용 이력)
create table if not exists point_history (
  id bigint generated by default as identity primary key,
  no integer not null,
  date text,
  type text,
  description text,
  amount integer default 0,
  balance integer default 0,
  created_at timestamp with time zone default now()
);

-- crm_statistics (CRM 발송 통계)
create table if not exists crm_statistics (
  id bigint generated by default as identity primary key,
  no integer not null,
  "campaignName" text,
  type text,
  "sendDate" text,
  "targetCount" integer default 0,
  "successCount" integer default 0,
  "failCount" integer default 0,
  cost integer default 0,
  created_at timestamp with time zone default now()
);

-- page_statistics (고객 유입 통계)
create table if not exists page_statistics (
  id bigint generated by default as identity primary key,
  no integer not null,
  date text,
  "pageUrl" text,
  visits integer default 0,
  "newVisits" integer default 0,
  "returnVisits" integer default 0,
  "avgStayTime" text,
  "deviceShare" text,
  created_at timestamp with time zone default now()
);

-- ============================================================
-- Row Level Security (RLS) 활성화
-- ============================================================
alter table customers enable row level security;
alter table send_history enable row level security;
alter table campaigns enable row level security;
alter table marketing_records enable row level security;
alter table point_history enable row level security;
alter table crm_statistics enable row level security;
alter table page_statistics enable row level security;

-- anon key로 읽기 허용 (필요에 따라 수정)
create policy "Allow anon read" on customers for select using (true);
create policy "Allow anon read" on send_history for select using (true);
create policy "Allow anon read" on campaigns for select to anon using (true);
create policy "Allow anon read" on marketing_records for select to anon using (true);
create policy "Allow anon read" on point_history for select to anon using (true);
create policy "Allow anon read" on crm_statistics for select to anon using (true);
create policy "Allow anon read" on page_statistics for select to anon using (true);

create policy "Allow anon insert" on campaigns for insert to anon with check (true);
