export type { ICustomerDto } from './ICustomerDto';
export type { ICampaignDto, ICampaignButtonDto } from './ICampaignDto';
export type { IMarketingDto } from './IMarketingDto';
export type { ICrmStatDto } from './ICrmStatDto';
export type { IPageStatDto } from './IPageStatDto';
export type { IPointHistoryDto } from './IPointHistoryDto';
export type { ISendHistoryDto } from './ISendHistoryDto';
export type { ISubscriptionDto } from './ISubscriptionDto';
export type { IPaymentHistoryDto } from './IPaymentHistoryDto';
export type { IServiceProductDto } from './IServiceProductDto';
export type { IBannerDto } from './IBannerDto';
export type { IBannerTemplateDto } from './IBannerTemplateDto';
export type { ICrmSummaryDto } from './ICrmSummaryDto';
